//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMigracion.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public string Accion { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
