//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlMigracion.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int Id { get; set; }
        public int IdViajero { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Destino { get; set; }
        public string Origen { get; set; }
        public string TipoSolicitud { get; set; }
        public int IdUsuario { get; set; }
        public int IdPuntoControl { get; set; }
    
        public virtual PuntosControl PuntosControl { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Viajeros Viajeros { get; set; }
    }
}
